version: '3.8'

# Deployment da app web Rotten Potatoes
services:
  rotten-potatoes:
    build:
      dockerfile: Dockerfile
      context: ./
    privileged: true
    restart: always
    container_name: ${CONTAINER_NAME}
    hostname: ${APP_NAME}
    ports:
      - 8081:${PORT_APP}
    expose:
      - ${PORT_APP}
    networks:
      - ${NETWORK}
    depends_on:
      - ${DEPENDS}
    environment:
      MONGODB_HOST: mongodb-rp
      MONGODB_USERNAME: mguser
      MONGODB_PASSWORD: mgpwd123
      MONGODB_PORT: ${MGDB_PORT}
      MONGODB_DB: ${MGDB_DB}

# Deployment do MongoDB
  mongodb-rp:
    image: mongo:5.0.5
    container_name: mongodb-rp
    hostname: mongodb-rp
    expose:
      - ${MGDB_PORT}
    ports:
      - ${MGDB_PORT}:${MGDB_PORT}
    networks:
      - ${NETWORK}
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mguser
      MONGO_INITDB_ROOT_PASSWORD: mgpwd123

# Instalação e configuração da interface do Mongo-Express para gerenciamento do banco via console web.
  mongodb-express-rp:
    image: mongo-express
    restart: always
    container_name: mongo-express-rp
    hostname: mongo-express-rp
    expose:
      - '8090'
    ports:
      - 8090:${PORT_LOCAL}
    networks:
      - ${NETWORK}
    depends_on:
      - ${DEPENDS}
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-rp
      ME_CONFIG_MONGODB_ADMINUSERNAME: mguser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mgpwd123
      ME_CONFIG_MONGODB_PORT: ${MGDB_PORT}


volumes:
  mongo_vol:

networks:
  mongo-net-rt:
    driver: bridge
