version: '3.8'

# Deployment da app web Rotten Potatoes
services:
  rotten-potatoes:
    build:
      dockerfile: Dockerfile
      context: ./
    privileged: true
    restart: always
    container_name: ${CONTAINER_NAME}
    hostname: ${APP_NAME}
    ports:
      - ${PORT_LOCAL_CONTAINER}:${PORT_APP}
    expose:
      - ${PORT_APP}
    networks:
      - ${NETWORK}
    depends_on:
      - ${DEPENDS}
    environment:
      MONGODB_HOST: ${MGDB_HOST}
      MONGODB_USERNAME: ${MGDB_USERNAME}
      MONGODB_PASSWORD: ${MGDB_PASSWORD}
      MONGODB_PORT: ${MGDB_PORT}
      MONGODB_DB: ${MGDB_DB}

# Deployment do MongoDB
  mongodb-rp:
    image: mongo:5.0.5
    container_name: ${MGDB_HOST}
    hostname: ${MGDB_HOST}
    expose:
      - ${MGDB_PORT}
    ports:
      - ${MGDB_PORT}:${MGDB_PORT}
    networks:
      - ${NETWORK}
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MGDB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MGDB_PASSWORD}

# Instalação e configuração da interface do Mongo-Express para gerenciamento do banco via console web.
  mongodb-express-rp:
    image: mongo-express
    restart: always
    container_name: ${EX_CONTAINER_NAME}
    hostname: ${EX_HOST_NAME}
    expose:
      - ${PORT_LOCAL_EXPRESS}
    ports:
      - ${PORT_LOCAL_EXPRESS}:${PORT_LOCAL_CONTAINER}
    networks:
      - ${NETWORK}
    depends_on:
      - ${DEPENDS}
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MGDB_HOST}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MGDB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MGDB_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MGDB_PORT}


volumes:
  mongo_vol:

networks:
  mongo-net-rt:
    driver: bridge
